package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Notificacion_comentario extends VerticalLayout {
	protected HorizontalLayout notificarComentarioLayout;
	protected Image fotoUsuarioComentario;
	protected Button usuarioComentario;
	protected Label comentarioLbl;
	protected Image publicacionComentario;
	protected HorizontalLayout notificarSeguidorLayout;
	protected Image fotoUsuarioSeguidor;
	protected Button usuarioSeguidor;
	protected HorizontalLayout notificarMeGustaLayout;
	protected Image fotoUsuarioMeGusta;
	protected Button usuarioMeGusta;
	protected Image publicacionMeGusta;
	protected HorizontalLayout solicitarSeguirLayout;
	protected Image fotoUsuarioSolicitud;
	protected Button usuarioSolicitud;
	protected Button confirmarSeguidorBtn;
	protected Button denegarSeguidorBtn;
	protected HorizontalLayout notificarEtiquetaLayout;
	protected Image fotoUsuarioEtiqueta;
	protected Button usuarioEtiqueta;
	protected Image publicacionEtiqueta;

	public Notificacion_comentario() {
		Design.read(this);
	}
}
