package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_usuario_inv_ventana extends VerticalLayout {
	protected VerticalLayout mainLayout;
	protected HorizontalLayout contentLayout;
	protected Image imagen_perfil_ajeno1;
	protected Label nombre_usuario2;
	protected Label nombre_usuario11;
	protected Button botonOpciones;
	protected GridLayout grid_informacionUsuario1;
	protected Label numPublicaciones;
	protected Button numSeguidores;
	protected Button numSeguidos;
	protected VerticalLayout seguirLayout;
	protected Button seguirBtn;
	protected AbsoluteLayout busquedaLayout;
	protected HorizontalLayout contentLayout1;
	protected Image fotoPerfil;
	protected Label nombreUsuario;
	protected Label usuarioLbl;

	public Ver_usuario_inv_ventana() {
		Design.read(this);
	}
}
